from sqlalchemy.orm import Session
from sqlalchemy.exc import IntegrityError
from fastapi import HTTPException
import models
import schemas

def get_atleta(db: Session, atleta_id: int):
   return db.query(models.Atleta).filter(models.Atleta.id == atleta_id).first()

def get_atletas(db: Session, skip: int = 0, limit: int = 10):
   return db.query(models.Atleta).offset(skip).limit(limit).all()

def create_atleta(db: Session, atleta: schemas.AtletaCreate):
   db_atleta = models.Atleta(**atleta.dict())
   try:
       db.add(db_atleta)
       db.commit()
       db.refresh(db_atleta)
       return db_atleta
   except IntegrityError:
       db.rollback()
       raise HTTPException(status_code=303, detail=f"JÃ¡ existe um atleta cadastrado com o cpf: {atleta.cpf}")
